### ISSUE TITLE
Support for Environment with Proxy and Windows Authentication

### ISSUE THREAD

**Issue by Linus62** [meancrazy/LINQPadOData4#10]
The actual Driver does not work with a proxy.
I made some fixes in the code that it worked for me. in the files CodeGenerationContext.cs and OData4DynamicDriver.cs. 
I zipped my project as an attachment.
[LINQPadOData4-1.0.0.0_forProxy.zip](https://github.com/meancrazy/LINQPadOData4/files/341316/LINQPadOData4-1.0.0.0_forProxy.zip)

**Comment by meancrazy** [comment]
Did you see the **[last](https://github.com/meancrazy/LINQPadOData4/releases/tag/1.0.3.3_1)** pre-release version? It's already have a proxy and win-auth support.
