### ISSUE TITLE
ODataLib 7.0.0

### ISSUE THREAD

**Issue by patrickmichalina** [meancrazy/LINQPadOData4#13]
Any plans to support the newer OData libraries?

**Comment by meancrazy** [comment]
Sure, waiting for https://github.com/OData/odata.net/issues/731

**Comment by meancrazy** [comment]
While we are waiting new libs try [this](/meancrazy/LINQPadOData4/releases/tag/1.0.3.6) build.

**Comment by tangrl** [comment]
Do we have progress on this one? It has been a while.

**Comment by meancrazy** [comment]
Still waiting for MS 😄  They says that it will be done on this week.
