### ISSUE TITLE
Error when adding WebApi OData service

### ISSUE THREAD

**Issue by chriscur** [meancrazy/LINQPadOData4#16]
When I expand a newly added connection I get a Populating message that simply goes away after a few seconds. When I hover over the connection I get an error.

```
Error: EdmParseException - Encountered the following errors when parsing the EDMX document:
XmlError: For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method. : (0, 0)
```

Linqpad 5.10.00
driver version  1.0.3.7 (869742f)

**Comment by meancrazy** [comment]
Please try [this](https://github.com/meancrazy/LINQPadOData4/files/880127/OData4DynamicDriver.zip) version and write about results.
