### ISSUE TITLE
CustomizedRequestMessage ignores system web proxy

### ISSUE THREAD

**Issue by maboivin** [meancrazy/LINQPadOData4#17]
The issue (found in v1.0.3.7) is that when you run Fiddler to debug your OData 4 queries, the system web proxy is ignored. Even if you check the "Use LINQPad web proxy" checkbox in the advanced properties, it's still ignored. You need to manually fill the info about the proxy (for fiddler, it's usually http://localhost:8888).

This is related to LINQPad.Util.GetWebProxy() that seems to be ignoring WebRequest.GetSystemWebProxy() (It may be a good idea to ask @albahari about the LINQPad utility method).

There is a workaround, re-register the proxy in the SendingRequest2 event:

```
this.SendingRequest2 += (s, e) =>
{
    ((HttpWebRequestMessage)e.RequestMessage).HttpWebRequest.Proxy = WebRequest.GetSystemWebProxy();
};
```
It would be nice if the driver would do it for us in the CustomizedRequestMessage implementation.

**Comment by meancrazy** [comment]
Hi! I've asked Joe for solution and 'm waiting answer.

**Comment by albahari** [comment]
LINQPad.Util.GetWebProxy() will return the proxy settings that users enter via the LINQPad UI. Does this answer your question?

`WebRequest.DefaultWebProxy = LINQPad.Util.GetWebProxy();   // This will work in your driver.`

**Comment by meancrazy** [comment]
So I can add an extra option:
 - [ ] use system proxy.

**Comment by maboivin** [comment]
Well, I think it's a bit more than that. I think the LINQPad proxy should be used first, if it's configured. If not, then the system proxy should be used if there's one. Otherwise, you should not use any proxy...

For example, the OData 3 driver based on WCF does that by default. When running Fiddler, you have nothing to configure and it uses the system proxy. If you remove the system proxy (ie: close Fiddler), the driver works fine also.

**Comment by albahari** [comment]
Sorry, my example was incomplete. To honor the system proxy, you need to do something like this:

```
var proxy = LINQPad.Util.GetWebProxy();
if (proxy != null) 
  WebRequest.DefaultWebProxy = proxy;
else
  WebRequest.DefaultWebProxy = WebRequest.GetSystemWebProxy();
```

In the OData 3 driver, I also handle the SendingRequest event, because setting the default web proxy is not enough:

```
dsContext.SendingRequest += (sender, e) =>
{
   var proxy = Util.GetWebProxy ();
   if (proxy != null) e.Request.Proxy = proxy;
}
```

An interesting point is that I'm pretty sure that the following code:

`WebRequest.DefaultWebProxy = WebRequest.GetSystemWebProxy();`

merely *restores* the default web proxy to what it was originally. IOW, it's a NOOP unless you've previously assigned DefaultWebProxy to something else.

**Comment by maboivin** [comment]
Maybe the easiest fix is to check if the proxy is null before assigning it here:
https://github.com/meancrazy/LINQPadOData4/blob/869742f3c2283f3d8379074aec4a69062e24c87d/CustomizedRequestMessage.cs#L10

**Comment by maboivin** [comment]
With the fix that was made, you absolutely need to check the "Use LINQPad web proxy" checkbox in the advanced properties which is not intuitive.

The way I see it is that you don't need to override the proxy when the returned proxy is null (there may already be something in the proxy and you don't have to set it to null). And I don't think you need to query the system proxy at all in the end.

So, I tried a version with the following code in CustomizedRequestMessage:
```
    var proxy = properties.GetWebProxy();
    if (proxy != null)
    {
        HttpWebRequest.Proxy = proxy;
    }
```

And the result is that I don't need to check the Use LINQPad web proxy at all and the system proxy is always used by default.

What do you think?

**Comment by meancrazy** [comment]
Hmm, I suppose "use LINQPad web proxy" check like "use web proxy", what's wrong 😹 . So we would have: system proxy (or none if it's unset) if check off and LINQPad proxy if check on. I'll fix them, thanks.
