### ISSUE TITLE
Allow invalid/untrusted SSL/HTTPS certificate

### ISSUE THREAD

**Issue by SanderSade** [meancrazy/LINQPadOData4#19]
At least for the localhost, but preferably as an option for all sites. 

Many sites use self-signed or otherwise invalid certificates while testing. This already exists for older version, see [this discussion](http://forum.linqpad.net/discussion/37/access-odata-feed-with-an-untrusted-ssl-certificate-from-linqpad).

**Comment by meancrazy** [comment]
This is already exists
![image](https://user-images.githubusercontent.com/1130419/29550784-4f655ae0-8718-11e7-8250-f4936b393240.png)
