### ISSUE TITLE
OData basic authorization

### ISSUE THREAD

**Issue by Jamaxack** [meancrazy/LINQPadOData4#20]
From LINQPad not able to authorize to OData. Using OData basic authorization.
## Assemblies affected 
LINQPad driver:
Name: OData 4
Version: 1.0.1.0
Author: Dimtrii Smirnov

OData endpoint: Microsoft.AspNet.OData v6.1.0(Latest at 23/11/2017)

LINQPad 5(Free Edition)  v5.26.01

## Reproduce steps
Custom AuthorizeAttribute is created:
```
public class ODataBasicAuthorizeAttribute : System.Web.Http.AuthorizeAttribute
 {
         public override void OnAuthorization(System.Web.Http.Controllers.HttpActionContext actionContext)
        {
            if (actionContext.Request.Headers.Authorization == null || actionContext.Request.Headers.Authorization.Scheme != "Basic")
            {
               
	    }
...
}
```
From LINQPad I have connection to OData endpoint and I'm able to see the table names:
![odataconnection](https://user-images.githubusercontent.com/5724537/33158146-22edb21e-d029-11e7-969f-4117575815ba.PNG)

Credentials are entered and pressing OK button:
![linqpadlogin](https://user-images.githubusercontent.com/5724537/33158159-45c0b70a-d029-11e7-9cc7-6f311f4b14f0.png)
## Expected result
 In OData endpoint custom class: `ODataBasicAuthorizeAttribute `, method: `OnAuthorization` ,`actionContext.Request.Headers.Authorization` should contain credentials that we entered from Login window(LINQPad) in screenshot.
## Actual result
In OData endpoint custom class: `ODataBasicAuthorizeAttribute `, method: `OnAuthorization` ,`actionContext.Request.Headers.Authorization` value is null
## Additional detail
In UI code there is functionality to select the type of authorization(Basic), but this choice is not shown in Login window in LINQPad:
https://github.com/meancrazy/LINQPadOData4/blob/d07ecbfa79e3fbb2eb977fe89b82662760002aa3/UI/ConnectionDialog.xaml#L26
Suggested fix:
It would be good if we can select Basic authorization type and login to access data

**Comment by meancrazy** [comment]
Please try latest release from this repo: https://github.com/meancrazy/LINQPadOData4/releases/download/1.0.3.8/OData4DynamicDriver.lpx

**Comment by Jamaxack** [comment]
Hi Dmitrii,
I got latest driver(1.0.3.8) and I'm able to select authentication type, what I need is [Basic authentication], but the `actionContext.Request.Headers.Authorization` is still `null`, even if I enter the credentials.

`Custom Headers` in `Advanced `section worked for me. I send authorization credentials with custom headers, but I think [Basic authentication] credentials should be sent in headers by default, so that way we don't have to sent with custom headers. **One note:** if you want to sent [Basic authentication] credentials in header please convert [username:password] to Base64 string.

Thank you,
