### ISSUE TITLE
Any plan to publish a new version for linqpad 6 ?

### ISSUE THREAD

**Issue by ochicaud** [meancrazy/LINQPadOData4#21]
Hello,
I use your odata v4 driver (1.0.3.8) every day. 
And I keep linqpad 5 only because your driver is only available on that version

Thanks !

**Comment by meancrazy** [comment]
Yep, I just published a new version on [NuGet](https://www.nuget.org/packages/OData4.LINQPadDriver/2.0.0).
Sorry for the delay.
