### ISSUE TITLE
The drive does not fetch entities along navigation relationships

### ISSUE THREAD

**Issue by michaelaltmann** [meancrazy/LINQPadOData4#3]
I have two entities defined, Product and Supplier and a one-to-many relationship from Product to Supplier Unless I am misunderstanding the LinqPad UI, the driver never fetches the Supplier for a product.  Is this supported?

**Comment by meancrazy** [comment]
Driver has a method .Expand(...). You can use it like

``` c#
Products.Expand(product => product.Supplier).ToList();
```

See also http://www.odata.org/getting-started/basic-tutorial/#expand

**Comment by michaelaltmann** [comment]
Thanks.  Is there a way to force it to use urls of the form 

```
Product(3)/Supplier 
```

rather than 

```
Product?$expand=Supplier
```

I need this because the relationship is defined in the OData model, but not in the Product CLR type on the server side.  My controller does have a GetSupplier method would provide the related supplier.

**Comment by meancrazy** [comment]
Sure,

``` c#
Products.Where(p => p.ID == 3).Select(p => p.Supplier).Single()
```

**Comment by michaelaltmann** [comment]
Thanks.  That does use the  Product(3)/Supplier URL when the Product class has a property called Supplier.  However, in my real application where I am building up the EDM model manually and adding the navigational property manually without having the Supplier property, LinqPad only makes a call to  Product(1).  Any ideas?  Here is the code I am using to build the EDM model relationship.

```
EdmNavigationPropertyInfo info = new EdmNavigationPropertyInfo();
            info.Name = relationshipName;
            info.Target = sourceEntityType;
            info.TargetMultiplicity = EdmMultiplicity.Many;
            EdmNavigationProperty navigation =
            sourceEntityType.AddUnidirectionalNavigation(info);
            sourceEntitySet.AddNavigationTarget(navigation, targetEntitySet);
```

**Comment by meancrazy** [comment]
Correct me: Your model has one Product entity set, two entity definitions Product and Supplier and the Product entity has an Supplier property. And there is no Supplier entity set?
